language: node_js

node_js:
  - "6.9"
  - "7.3"

os:
  - linux

sudo:
  - true

dist: 
  - precise

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

deploy:
  provider: npm
  email: antirek@yandex.ru
  api_key:
    secure: e1533d0a-6243-4ced-ac36-e413a972ec63
  on:
    repo: antirek/cyberplat